"""Привязка пользователей к данным 2

Revision ID: 546a87a282b5
Revises: f999aac9e097
Create Date: 2025-12-16 00:15:13.929987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546a87a282b5'
down_revision: Union[str, Sequence[str], None] = 'f999aac9e097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'user_id')
    # ### end Alembic commands ###
