"""Переделана таблица уроков 2 раз

Revision ID: d6b7e0d1242b
Revises: 4162a38755a3
Create Date: 2025-11-27 16:59:17.079782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b7e0d1242b'
down_revision: Union[str, Sequence[str], None] = '4162a38755a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plans', sa.Column('end', sa.DateTime(), nullable=False))
    op.drop_column('lesson_plans', 'bio')
    op.drop_column('lesson_plans', 'subtopic')
    op.drop_column('lesson_plans', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plans', sa.Column('topic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lesson_plans', sa.Column('subtopic', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('lesson_plans', sa.Column('bio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('lesson_plans', 'end')
    # ### end Alembic commands ###
